const STORAGE_KEY = "yv_pamela_flashcards_v1";
const flashcards = [
  {english:"I am",portuguese:"eu sou / estou"},{english:"you are",portuguese:"você é / está"},{english:"he is",portuguese:"ele é / está"},{english:"she is",portuguese:"ela é / está"},{english:"we are",portuguese:"nós somos / estamos"},{english:"they are",portuguese:"eles/elas são / estão"},{english:"I am here",portuguese:"eu estou aqui"},{english:"He is my son",portuguese:"ele é meu filho"},{english:"Are you okay?",portuguese:"você está bem?"},{english:"Is it serious?",portuguese:"é sério?"},{english:"She isn't home",portuguese:"ela não está em casa"},{english:"your son",portuguese:"seu filho"},{english:"you're my friend",portuguese:"você é meu amigo"},{english:"wake up",portuguese:"acordar"},{english:"get up",portuguese:"levantar"},{english:"brush my teeth",portuguese:"escovar meus dentes"},{english:"take a shower",portuguese:"tomar banho"},{english:"eat breakfast",portuguese:"tomar café da manhã"},{english:"go to work",portuguese:"ir para o trabalho"},{english:"Do you drink coffee?",portuguese:"você bebe café?"},{english:"Does she work?",portuguese:"ela trabalha?"},{english:"I don't wake up late",portuguese:"eu não acordo tarde"},{english:"He doesn't drink soda",portuguese:"ele não bebe refrigerante"},{english:"airport",portuguese:"aeroporto"},{english:"flight",portuguese:"voo"},{english:"coffee",portuguese:"café"},{english:"tired",portuguese:"cansada"}
];
let state = loadState(); let queue = buildQueue(); let currentIndex = queue[0] ?? 0;
function loadState(){ try{return JSON.parse(localStorage.getItem(STORAGE_KEY)) || {}}catch{return {}} }
function saveState(){ localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }
function scoreFor(i){ const s=state[i]||{again:0,hard:0,easy:0}; return 1 + s.again*4 + s.hard*2 - s.easy; }
function buildQueue(){ return flashcards.map((_,i)=>i).sort((a,b)=>scoreFor(b)-scoreFor(a)); }
function render(){ const card=flashcards[currentIndex]; document.getElementById("flashEnglish").textContent=card.english; document.getElementById("flashPortuguese").textContent=card.portuguese; document.getElementById("flashcard").classList.remove("flipped","slide-left","slide-right"); updateStats(); }
function updateStats(){ let known=0,review=0; flashcards.forEach((_,i)=>{ const s=state[i]||{}; if((s.easy||0)>=2 && !(s.again||0)) known++; else review++; }); document.getElementById("knownCount").textContent=known; document.getElementById("reviewCount").textContent=review; document.getElementById("totalCount").textContent=flashcards.length; document.getElementById("progressNote").textContent=`Card ${queue.indexOf(currentIndex)+1 || 1} / ${flashcards.length}`; }
function flipCard(){ document.getElementById("flashcard").classList.toggle("flipped"); }
function speak(text){ if(!window.speechSynthesis)return; window.speechSynthesis.cancel(); const u=new SpeechSynthesisUtterance(text); u.lang="en-US"; u.rate=.84; window.speechSynthesis.speak(u); }
function speakCard(e){ if(e) e.stopPropagation(); speak(flashcards[currentIndex].english); }
function gradeCard(type){ state[currentIndex]=state[currentIndex]||{again:0,hard:0,easy:0}; state[currentIndex][type]=(state[currentIndex][type]||0)+1; if(type==="easy") state[currentIndex].again=Math.max(0,(state[currentIndex].again||0)-1); saveState(); nextCard(); }
function nextCard(){ const el=document.getElementById("flashcard"); el.classList.add("slide-left"); setTimeout(()=>{ queue=buildQueue(); const pos=queue.indexOf(currentIndex); currentIndex=queue[(pos+1)%queue.length]; render(); },220); }
function resetStats(){ localStorage.removeItem(STORAGE_KEY); state={}; queue=buildQueue(); currentIndex=queue[0]; render(); }
let touchStartX=0; const el=document.getElementById("flashcard"); el.addEventListener("touchstart",e=>{touchStartX=e.changedTouches[0].screenX}); el.addEventListener("touchend",e=>{ const diff=e.changedTouches[0].screenX-touchStartX; if(Math.abs(diff)>70) nextCard(); });
render();
